#!/usr/bin/env bash

SCRIPT_DIRECTORY=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

$SCRIPT_DIRECTORY/generate_env
docker-compose --file "$SCRIPT_DIRECTORY/docker-compose.yml" run --rm --name map_array map_array-application
